name: hauxe
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  shared_preferences: ^2.0.15  # Para guardar preferencias
  animate_do: ^3.3.4
  nice_intro: ^0.2.1
  water_drop_nav_bar: ^2.2.0+5
  shrink_sidemenu: ^2.0.0+2-null-safety
  flutter_blurhash: ^0.6.4
  bottom_navy_bar: ^6.0.0
  contained_tab_bar_view_with_custom_page_navigator: ^0.1.3
  stacked_notification_cards: ^0.1.0-dev.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  panorama: ^0.4.1
  #firebase_core: ^1.0.1
  #cloud_firestore: ^1.0.1
  #firebase_auth: ^1.0.1
  google_sign_in: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  generate: true 
  assets:
    - assets/intro_screen/welcome.jpg
    - assets/intro_screen/g.png
    - assets/intro_screen/Gt.png
    - assets/intro_screen/Pt.png
    - assets/intro_screen/icon.png
    - assets/intro_screen/hauxe.png
    - lib/l10n/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
